apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5gpd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5gpd
    app.kubernetes.io/part-of: cin4s-839-0023-app
  name: devfile-sample-5gpd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-5gpd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-5gpd
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0023-tenant/cin4s-839-0023-app/devfile-sample-5gpd@sha256:e758961f3d62171373b53ef1b76fc92c58c8776dbb05a11f94e5ccdc251a9bf9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
